name: Compile Resume

on:
  push:
    paths:
      - 'main.tex'
      - '.github/workflows/compile-resume.yml'
  pull_request:
    paths:
      - 'main.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: false
          latexmk_shell_escape: true

      - name: Rename PDF to resume.pdf
        run: mv main.pdf resume.pdf

      - name: Upload compiled resume
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf

      - name: Configure git user
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit updated resume.pdf
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if git diff --quiet -- resume.pdf; then
            echo "No changes to commit."
          else
            git add resume.pdf
            git commit -m "Update compiled resume.pdf"
            git push
          fi
